include:
- issue-comment.js
kind: ArchiveUploadSpec
name: issue-comment-js

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: issue-comment-js-gtdy
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://issue-comment-js
  environment:
    name: hubotjs
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: issue-comment
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 1
      MinScale: 0
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: hubotjs
    namespace: default
  package:
    packageref:
      name: issue-comment-js-gtdy
      namespace: default
  resources: {}
  secrets:
  - name: gh-applets
    namespace: default
